name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.TAGBOT_SSH_KEY }}
          ssh_password: ${{ secrets.TAGBOT_SSH_KEY_PASSWORD }}
          gpg: ${{ secrets.TAGBOT_GPG_KEY }}
          gpg_password: ${{ secrets.TAGBOT_GPG_KEY_PASSWORD }}
